name = "TodoList"
uuid = "7f8c6f20-4e98-4d72-b8e1-8e9f2c3d4a5b"
authors = ["Dustin Thomas <dustinthomas>"]
version = "0.1.0"

[deps]
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
julia = "1.12"
SQLite = "1.6"
DBInterface = "2.5"
