name = "TodoList"
uuid = "76257cc3-1599-4723-8b5e-57b46f78697b"
version = "0.1.0"
authors = ["Dustin Hess <dustin.phys@gmail.com>"]

[deps]
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"

[compat]
Comonicon = "1.0.8"
DBInterface = "2.6.1"
SQLite = "1.6.1"
