name = "TodoList"
uuid = "7f8c6f20-4e98-4d72-b8e1-8e9f2c3d4a5b"
version = "0.1.0"
authors = ["Dustin Thomas <dustinthomas>"]

[deps]
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
Term = "22787eb5-b846-44ae-b979-8e399b8463ab"

[compat]
DBInterface = "2.5"
SQLite = "1.6"
Term = "2.0.8"
julia = "1.12"
